### PR TITLE
Force HBM off when display off

### PR DESCRIPTION
**Pull request by TaeHagen**
https://github.com/J0SH1X/android_device_oneplus_fajita/pull/1

### CODE REVIEW

**Comment by TaeHagen** [comment]
Or you could use commits here https://github.com/SevralT/kernel_oneplus_sdm845/commits/12.0-vendor

**Comment by J0SH1X** [comment]
> Or you could use commits here https://github.com/SevralT/kernel_oneplus_sdm845/commits/12.0-vendor

nah he uses a different kernel this cant be applied to plain los kernel also its not working properly and causes phone to flicker he said

**Comment by TaeHagen** [comment]
Well my fork works well for me so you can try that

**Comment by TaeHagen** [comment]
He used a patch for the sm8150 kernel I tried to apply earlier but had so much difference I just wrote my own and submitted this PR. When I found his code I assumed he had adapted it to this kernel, but I guess he's just using the other one.

**Comment by J0SH1X** [comment]
> Well my fork works well for me so you can try that

seems like your fork contains my ugly try to add the sm8150 patch to our kernel , i would strongly recommend not using that also kernel has a rebased los 19 branch now started from 18.1 kernel again

**Comment by J0SH1X** [comment]
> Well my fork works well for me so you can try that

actually works now , but fingerprint seems to be dead after a unlock or 2 with hold a little longer message

**Comment by TaeHagen** [comment]
Huh normally that happens when HBM is not activated. When turning brightness down to minimum and pressing on the fp, does the circle light up extremely brightly? It's working for me so not sure. Are you using my qcom-caf display fork?

**Comment by J0SH1X** [comment]
> Huh normally that happens when HBM is not activated. When turning brightness down to minimum and pressing on the fp, does the circle light up extremely brightly? It's working for me so not sure. Are you using my qcom-caf display fork?

nope the circle does not light up extremly bightly
i did drop the systemui patch in favor of this pr im not quite sure what im doing wrong

**Comment by TaeHagen** [comment]
So things I'd check:
Add a log here and check if this if statement is entered when touching the fp sensor
https://github.com/TaeHagen/android_hardware_qcom_display/blob/lineage-19.0-caf-sdm845/sdm/libs/hwc2/hwc_layers.cpp#L257

If it is entered, I would make sure the vendor libraries (libsdedrm and libsdmcore) are properly being copied over the ones copied from source (libsdmcore can also be compiled from source, but lacks modifications)

If it isn't entered, I would ensure this patch https://review.lineageos.org/c/LineageOS/android_frameworks_native/+/317924 is properly setting the z-layer of the UDFPS layer to 0xfc8. It should be set here: https://github.com/LineageOS/android_frameworks_native/blob/126cb3dcc3cdcbd88888bbb0a7e022e7baebd2e2/services/surfaceflinger/CompositionEngine/src/OutputLayer.cpp#L415 That should satisfy the condition above

**Comment by TaeHagen** [comment]
I also dropped the sysui patch that shouldn't be an issue

**Pull request merged**
